feat: separate legacy

diff --git a/docker/Dockerfile b/docker/Dockerfile
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -1,27 +1,33 @@
+FROM oven/bun:1-alpine AS BUN
+
 # Install dependencies only when needed
-FROM node:18.2-alpine AS deps
+FROM BUN AS deps
 # Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
-RUN apk add --no-cache libc6-compat
+# RUN apk add --no-cache libc6-compat
 WORKDIR /app
 
 # Install dependencies based on the preferred package manager
-COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
-RUN \
-  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
-  elif [ -f package-lock.json ]; then npm ci; \
-  elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i --frozen-lockfile; \
-  else echo "Lockfile not found." && exit 1; \
-  fi
+# COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
+# RUN \
+#   if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+#   elif [ -f package-lock.json ]; then npm ci; \
+#   elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i --frozen-lockfile; \
+#   else echo "Lockfile not found." && exit 1; \
+#   fi
+RUN apk add git
+
+COPY package.json bun.lockb ./
+RUN bun install
 
 # Rebuild the source code only when needed
-FROM node:18.2-alpine AS builder
+FROM BUN AS builder
 WORKDIR /app
 COPY --from=deps /app/node_modules ./node_modules
 COPY . .
 
-RUN yarn build:ncc
+RUN bun build:ncc
 
-FROM node:18.2-alpine AS runner
+FROM BUN AS runner
 WORKDIR /app
 
 ENV NODE_ENV production
@@ -38,4 +44,4 @@ EXPOSE 3000
 ENV PORT 3000
 
 
-CMD ["node", "index.js"]
+CMD ["bun", "index.js"]
