chore: change build from bun to node 20

diff --git a/docker/Dockerfile b/docker/Dockerfile
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -1,33 +1,33 @@
-FROM oven/bun:1-alpine AS BUN
+FROM node:20-alpine AS base
 
 # Install dependencies only when needed
-FROM BUN AS deps
+FROM base AS deps
 # Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
 # RUN apk add --no-cache libc6-compat
 WORKDIR /app
 
 # Install dependencies based on the preferred package manager
-# COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
-# RUN \
-#   if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
-#   elif [ -f package-lock.json ]; then npm ci; \
-#   elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i --frozen-lockfile; \
-#   else echo "Lockfile not found." && exit 1; \
-#   fi
-RUN apk add git
+COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
+RUN \
+  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+  elif [ -f package-lock.json ]; then npm ci; \
+  elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i --frozen-lockfile; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
+# RUN apk add git
 
-COPY package.json bun.lockb ./
-RUN bun install
+# COPY package.json bun.lockb ./
+# RUN bun install
 
 # Rebuild the source code only when needed
-FROM BUN AS builder
+FROM base AS builder
 WORKDIR /app
 COPY --from=deps /app/node_modules ./node_modules
 COPY . .
 
-RUN bun build:ncc
+RUN yarn build:ncc
 
-FROM BUN AS runner
+FROM base AS runner
 WORKDIR /app
 
 ENV NODE_ENV production
@@ -44,4 +44,4 @@ EXPOSE 3000
 ENV PORT 3000
 
 
-CMD ["bun", "index.js"]
+CMD ["node", "index.js"]
